### PR TITLE
Fix : Safari doesn't fire 'change' event when fileOpen is called(#107)

### LINKED ISSUE #107: Safari doesn't fire 'change' event when fileOpen is called
Testing the demo https://browser-fs-access.glitch.me on Safari `Version 15.4 (17613.1.17.1.13)`, I can see that the browser does not consistently resolve the promise for fileOpen and sometimes simply doesn't return a file.

### PR DESCRIPTION
**Pull request by Barba828**
input file is required in the DOM for working in Safari

### CODE REVIEW

**Comment by tomayac** [comment]
@Barba828 Thanks for the PR. Are you in a position to sign the CLA?

**Comment by Barba828** [comment]
> @Barba828 Thanks for the PR. Are you in a position to sign the CLA?

OK, I have signed the CLA :)

**Comment by tomayac** [comment]
Thanks for signing the CLA. I'm currently traveling, but hope to be able to merge this on Friday.

**Comment by tomayac** [comment]
Thanks, deployed as `v0.30.0`.

**Pull request merged**
