### PR TITLE
Bundle to esm and cjs

### PR DESCRIPTION
**Pull request by steveruizok**
This PR changes the build process so that the library outputs a format in both commonjs and esmodules.

### CODE REVIEW

**Comment by tomayac** [comment]
@steveruizok In order to land this, could I ask you to [make the bot 🤖 happy](https://github.com/GoogleChromeLabs/browser-fs-access/pull/83#issuecomment-961940373)?

**Comment by steveruizok** [comment]
Done! (I think)

**Comment by tomayac** [comment]
@steveruizok, once you have done the work the bot asks you to do, you need to respond here with "@googlebot I signed it!". (Sorry for the hassle.)

**Comment by tomayac** [comment]
Oh, looks like as long as anyone responds with the magic phrase the bot is happy (if you have signed the thing). So ignore. Thank you!

**Review by tomayac — APPROVED** [review]
LGTM, approval

Thanks, and sorry for letting this hang so long… I'll fix the conflicts on my side.

**Pull request merged**
